steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '--build-arg'
      - 'VITE_API_URL=${_API_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/onshore-frontend'
      - '.'
    env:
      - 'VITE_API_URL=${_API_URL}'

images:
  - 'gcr.io/$PROJECT_ID/onshore-frontend'
